apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-server
  labels:
    app: {{ .Values.name }}
    component: server
  {{- if .Values.service.annotations.enabled }}
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"{{ .Values.server.port }}":{}}}'
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}
    component: server
